In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:

df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

| Column        | المعنى بالإنجليزي   | الشرح بالعربي                                                    |
| ------------- | ------------------- | ---------------------------------------------------------------- |
| Row ID        | Unique Row Number   | رقم فريد لكل صف في الداتا                                        |
| Order ID      | Order Identifier    | رقم الطلب الذي قام به العميل                                     |
| Order Date    | Date of Order       | تاريخ عمل الطلب                                                  |
| Ship Date     | Shipping Date       | تاريخ شحن الطلب للعميل                                           |
| Ship Mode     | Shipping Method     | طريقة الشحن (Standard – First Class – Same Day)                  |
| Customer ID   | Customer Identifier | رقم تعريف العميل                                                 |
| Customer Name | Customer Name       | اسم العميل                                                       |
| Segment       | Customer Segment    | نوع العميل (Consumer – Corporate – Home Office)                  |
| Country       | Country             | الدولة                                                           |
| City          | City                | المدينة                                                          |
| State         | State               | المحافظة أو الولاية                                              |
| Postal Code   | Postal Code         | الرمز البريدي                                                    |
| Region        | Region              | المنطقة الجغرافية (East – West – Central – South)                |
| Product ID    | Product Identifier  | رقم تعريف المنتج                                                 |
| Category      | Product Category    | الفئة الرئيسية للمنتج (Furniture – Office Supplies – Technology) |
| Sub-Category  | Product Subcategory | الفئة الفرعية للمنتج (Chairs – Phones – Storage...)              |
| Product Name  | Product Name        | اسم المنتج                                                       |
| Sales         | Sales Amount        | قيمة المبيعات بالدولار                                           |
| Quantity      | Quantity Sold       | عدد القطع المباعة                                                |
| Discount      | Discount Rate       | نسبة الخصم على المنتج                                            |
| Profit        | Profit Amount       | الربح الناتج من بيع المنتج                                       |

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [5]:
df.drop(columns=["Row ID"], inplace=True)
df.reset_index(inplace=True, drop=True)

In [6]:
df.isna().sum()

Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   object
 2   Ship Date      9994 non-null   object
 3   Ship Mode      9994 non-null   object
 4   Customer ID    9994 non-null   object
 5   Customer Name  9994 non-null   object
 6   Segment        9994 non-null   object
 7   Country        9994 non-null   object
 8   City           9994 non-null   object
 9   State          9994 non-null   object
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   object
 12  Product ID     9994 non-null   object
 13  Category       9994 non-null   object
 14  Sub-Category   9994 non-null   object
 15  Product Name   9994 non-null   object
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: float64(3), int64(2), object(15)
memory usage: 1.5+ MB

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [9]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [10]:
df['AVG Shipping Time'] = (df['Ship Date'] - df['Order Date']).dt.days
df.reset_index(inplace=True, drop=True)

In [11]:
df.describe()

,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit,AVG Shipping Time
count,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896,3.958175
min,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000,0.000000
25%,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750,3.000000
50%,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500,4.000000
75%,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000,5.000000
max,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000,7.000000
std,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108,1.747567

In [12]:
IQR= 209.940000-17.280000
upper= 209.940000 + 1.5*IQR
lower= 17.280000 - 1.5*IQR

In [13]:
upper

498.93

In [14]:
df[(df['Sales']>=upper) & (df['Sub-Category']=='Machines')].head(30)

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time
165,CA-2014-139892,2014-09-08,2014-09-12,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,Texas,...,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952,8,0.4,-1359.9920,4
215,CA-2015-146262,2015-01-02,2015-01-09,Standard Class,VW-21775,Victoria Wilson,Corporate,United States,Medina,Ohio,...,East,TEC-MA-10000864,Technology,Machines,Cisco 9971 IP Video Phone Charcoal,1188.000,9,0.7,-950.4000,7
262,US-2014-106992,2014-09-19,2014-09-21,Second Class,SB-20290,Sean Braxton,Corporate,United States,Houston,Texas,...,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,3059.982,3,0.4,-509.9970,2
263,US-2014-106992,2014-09-19,2014-09-21,Second Class,SB-20290,Sean Braxton,Corporate,United States,Houston,Texas,...,Central,TEC-MA-10003353,Technology,Machines,Xerox WorkCentre 6505DN Laser Multifunction Pr...,2519.958,7,0.4,-251.9958,2
318,CA-2014-164973,2014-11-04,2014-11-09,Standard Class,NM-18445,Nathan Mautz,Home Office,United States,New York City,New York,...,East,TEC-MA-10002927,Technology,Machines,Canon imageCLASS MF7460 Monochrome Digital Las...,3991.980,2,0.0,1995.9900,5
436,CA-2016-147375,2016-06-12,2016-06-14,Second Class,PO-19180,Philisse Overcash,Home Office,United States,Chicago,Illinois,...,Central,TEC-MA-10002937,Technology,Machines,Canon Color ImageCLASS MF8580Cdw Wireless Lase...,1007.979,3,0.3,43.1991,2
683,US-2017-168116,2017-11-04,2017-11-04,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,North Carolina,...,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904,0
977,CA-2017-159366,2017-01-07,2017-01-10,First Class,BW-11110,Bart Watters,Corporate,United States,Detroit,Michigan,...,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,3059.982,2,0.1,679.9960,3
1022,CA-2015-124450,2015-04-27,2015-05-03,Standard Class,GT-14710,Greg Tran,Consumer,United States,Washington,District of Columbia,...,East,TEC-MA-10004212,Technology,Machines,Cisco SPA525G2 5-Line IP Phone,1379.920,8,0.0,648.5624,6
1085,US-2016-143819,2016-03-01,2016-03-05,Standard Class,KD-16270,Karen Daniels,Consumer,United States,Yonkers,New York,...,East,TEC-MA-10003979,Technology,Machines,Ativa V4110MDD Micro-Cut Shredder,4899.930,7,0.0,2400.9657,4
1144,CA-2014-146969,2014-09-29,2014-10-03,Standard Class,AP-10915,Arthur Prichep,Consumer,United States,Los Angeles,California,...,West,TEC-MA-10004241,Technology,Machines,Star Micronics TSP800 TSP847IIU Receipt Printer,686.320,2,0.2,223.0540,4
1340,CA-2017-113481,2017-01-02,2017-01-04,First Class,AS-10045,Aaron Smayling,Corporate,United States,Jacksonville,North Carolina,...,South,TEC-MA-10002178,Technology,Machines,Cisco CP-7937G Unified IP Conference Station P...,695.700,2,0.5,-27.8280,2
1454,CA-2016-133711,2016-11-26,2016-11-29,First Class,MC-17425,Mark Cousins,Corporate,United States,Mobile,Alabama,...,South,TEC-MA-10000010,Technology,Machines,Hewlett-Packard Deskjet 3050a All-in-One Color...,3040.000,8,0.0,1459.2000,3
1833,CA-2017-162691,2017-08-01,2017-08-07,Standard Class,AS-10045,Aaron Smayling,Corporate,United States,Austin,Texas,...,Central,TEC-MA-10000488,Technology,Machines,Bady BDG101FRU Card Printer,1439.982,3,0.4,-263.9967,6
1912,CA-2017-121503,2017-07-03,2017-07-06,Second Class,FH-14275,Frank Hawley,Corporate,United States,Houston,Texas,...,Central,TEC-MA-10003674,Technology,Machines,Hewlett-Packard Deskjet 5550 Printer,597.132,3,0.4,49.7610,3
2182,CA-2016-128818,2016-05-07,2016-05-11,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,New York City,New York,...,East,TEC-MA-10000488,Technology,Machines,Bady BDG101FRU Card Printer,3999.950,5,0.0,1159.9855,4
2418,CA-2016-107202,2016-05-21,2016-05-28,Standard Class,LC-16930,Linda Cazamias,Corporate,United States,Sparks,Nevada,...,West,TEC-MA-10000112,Technology,Machines,Panasonic KX MB2061 Multifunction Printer,2396.400,10,0.2,179.7300,7
2602,CA-2016-165848,2016-06-04,2016-06-04,Same Day,EN-13780,Edward Nazzal,Consumer,United States,New York City,New York,...,East,TEC-MA-10003356,Technology,Machines,Panasonic KX MC6040 Color Laser Multifunction ...,1349.850,3,0.0,364.4595,0
2628,US-2017-165344,2017-11-13,2017-11-15,First Class,SB-20290,Sean Braxton,Corporate,United States,Springfield,Ohio,...,East,TEC-MA-10002210,Technology,Machines,Epson TM-T88V Direct Thermal Printer - Monochr...,652.995,7,0.7,-935.9595,2
2696,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,...,South,TEC-MA-10003626,Technology,Machines,Hewlett-Packard Deskjet 6540 Color Inkjet Printer,821.300,4,0.5,-16.4260,5
2697,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,...,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784,5
2709,CA-2015-121797,2015-01-30,2015-02-06,Standard Class,CC-12145,Charles Crestani,Consumer,United States,Los Angeles,California,...,West,TEC-MA-10000488,Technology,Machines,Bady BDG101FRU Card Printer,1919.976,3,0.2,215.9973,7
2838,CA-2016-147368,2016-06-09,2016-06-12,First Class,TC-21295,Toby Carlisle,Consumer,United States,Tallahassee,Florida,...,South,TEC-MA-10002178,Technology,Machines,Cisco CP-7937G Unified IP Conference Station P...,695.700,2,0.5,-27.8280,3
3011,CA-2017-134845,2017-04-17,2017-04-23,Standard Class,SR-20425,Sharelle Roach,Home Office,United States,Louisville,Colorado,...,West,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,2549.985,5,0.7,-3399.9800,6
3112,CA-2016-150350,2016-08-23,2016-08-30,Standard Class,MS-17770,Maxwell Schwartz,Consumer,United States,Seattle,Washington,...,West,TEC-MA-10001972,Technology,Machines,Okidata C331dn Printer,837.600,3,0.2,62.8200,7
3151,CA-2015-147830,2015-12-15,2015-12-18,First Class,NF-18385,Natalie Fritzler,Consumer,United States,Newark,Ohio,...,East,TEC-MA-10000418,Technology,Machines,Cubify CubeX 3D Printer Double Head Print,1799.994,2,0.7,-2639.9912,3
3295,CA-2017-113418,2017-10-01,2017-10-03,First Class,CM-12655,Corinna Mitchell,Home Office,United States,New York City,New York,...,East,TEC-MA-10002428,Technology,Machines,Fellowes Powershred HS-440 4-Sheet High Securi...,1704.890,11,0.0,767.2005,2
3298,CA-2017-136308,2017-11-16,2017-11-16,Same Day,MW-18235,Mitch Willingham,Corporate,United States,San Francisco,California,...,West,TEC-MA-10000488,Technology,Machines,Bady BDG101FRU Card Printer,1919.976,3,0.2,215.9973,0
3424,CA-2016-134803,2016-05-28,2016-06-03,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Los Angeles,California,...,West,TEC-MA-10001972,Technology,Machines,Okidata C331dn Printer,558.400,2,0.2,41.8800,6
3569,CA-2017-168109,2017-07-03,2017-07-03,Same Day,JK-15640,Jim Kriz,Home Office,United States,Seattle,Washington,...,West,TEC-MA-10001148,Technology,Machines,Okidata MB491 Multifunction Printer,2395.200,6,0.2,209.5800,0

In [15]:
df[df['Sales']==df['Sales'].max()]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time
2697,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,...,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.48,6,0.5,-1811.0784,5

In [16]:
df[df['Sub-Category']=='Machines']['Product Name'].nunique()

63

In [17]:
df['year_of_order'] = df['Order Date'].dt.year
df['month_of_order'] = df['Order Date'].dt.month
df['day_of_order'] = df['Order Date'].dt.day

In [18]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time,year_of_order,month_of_order,day_of_order
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,8
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,8
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,12
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,11
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,11

In [19]:
total_salary = df['Sales'].sum()
print("Total Sales:", total_salary)
total_profit = df['Profit'].sum()
print("Total Profit:", total_profit)
avg_discount = df['Discount'].mean()
print("Average Discount:", avg_discount)
total_customers = df['Customer ID'].nunique()
print("Total Customers:", total_customers)
total_orderings = df['Order ID'].nunique()
print("Total Orderings:", total_orderings)

Total Sales: 2297200.8603
Total Profit: 286397.0217
Average Discount: 0.1562027216329798
Total Customers: 793
Total Orderings: 5009

In [20]:
max_discount = df['Discount'].max()
print("Maximum Discount:", max_discount)

Maximum Discount: 0.8

In [21]:
df[df['Discount']>=0.30]['Profit'].sum()

np.float64(-135376.056)

In [22]:
df[df['Discount']<=0.40]['Profit'].sum()

np.float64(385955.61220000003)

In [23]:
df[df['Discount']==0.30]['Profit'].sum()

np.float64(-10369.277399999999)

In [24]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time,year_of_order,month_of_order,day_of_order
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,8
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,8
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,12
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,11
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,11

In [25]:
total_salary_of_year = df.pivot_table(values='Profit', index='year_of_order',columns='month_of_order', aggfunc='sum')
#total_salary_of_year.sort_values(by='Profit', ascending=False)
total_salary_of_year

month_of_order,1,2,3,4,5,6,7,8,9,10,11,12
year_of_order,,,,,,,,,,,,
2014,2450.1907,862.3084,498.7299,3488.8352,2738.7096,4976.5244,-841.4826,5318.1050,8328.0994,3448.2573,9292.1269,8983.5699
2015,-3281.0070,2813.8508,9732.0978,4187.4962,4667.8690,3335.5572,3288.6483,5355.8084,8209.1627,2817.3660,12474.7884,8016.9659
2016,2824.8233,5004.5795,3611.9680,2977.8149,8662.1464,4750.3781,4432.8779,2062.0693,9328.6576,16243.1425,4011.4075,17885.3093
2017,7140.4391,1613.8720,14751.8915,933.2900,6342.5828,8223.3357,6952.6212,9040.9557,10991.5556,9275.2755,9690.1037,8483.3468

In [61]:
total_profit_of_year = df.pivot_table(values='Profit', index='year_of_order', aggfunc='sum')
total_profit_of_year.sort_values(by='Profit', ascending=False)

                   Profit
year_of_order
2017           93439.2696
2016           81795.1743
2015           61618.6037
2014           49543.9741

In [62]:
total_sales_of_year = df.pivot_table(values='Sales', index='year_of_order', aggfunc='sum')
total_sales_of_year.sort_values(by='Sales', ascending=False)

                     Sales
year_of_order
2017           733215.2552
2016           609205.5980
2014           484247.4981
2015           470532.5090

In [27]:
total_salary_of_month = df.pivot_table(values='Profit', index='month_of_order', aggfunc='sum')
total_salary_of_month.sort_values(by='Profit', ascending=False)

                    Profit
month_of_order
12              43369.1919
9               36857.4753
11              35468.4265
10              31784.0413
3               28594.6872
5               22411.3078
8               21776.9384
6               21285.7954
7               13832.6648
4               11587.4363
2               10294.6107
1                9134.4461

In [28]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [29]:
Ship_Mode = df.pivot_table( index='Ship Mode',values='Profit', aggfunc='mean')
Ship_Mode.reset_index(inplace=True)
Ship_Mode.sort_values(by='Profit', ascending=False, inplace=True)
Ship_Mode

        Ship Mode     Profit
0     First Class  31.839948
2    Second Class  29.535545
1        Same Day  29.266591
3  Standard Class  27.494770

In [30]:
df[(df['Discount']>=0.30) & (df['year_of_order']==2017) ]['Profit'].sum()

np.float64(-47569.8998)

In [31]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time,year_of_order,month_of_order,day_of_order
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,8
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,8
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,12
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,11
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,11

In [32]:
df[df['Profit']==df['Profit'].max()]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time,year_of_order,month_of_order,day_of_order
6826,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,...,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.976,7,2016,10,2

In [33]:
df[df['Customer Name']=='Tamara Chand'].head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time,year_of_order,month_of_order,day_of_order
2072,CA-2016-129693,2016-11-26,2016-12-02,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Seattle,Washington,...,Binders,Newell 3-Hole Punched Plastic Slotted Magazine...,7.312,2,0.2,2.5592,6,2016,11,26
3185,CA-2014-123498,2014-11-07,2014-11-09,First Class,TC-20980,Tamara Chand,Corporate,United States,Houston,Texas,...,Binders,Satellite Sectional Post Binders,26.046,3,0.8,-44.2782,2,2014,11,7
3186,CA-2014-123498,2014-11-07,2014-11-09,First Class,TC-20980,Tamara Chand,Corporate,United States,Houston,Texas,...,Envelopes,Staple envelope,74.352,3,0.2,26.9526,2,2014,11,7
6825,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,...,Storage,Acco Perma 4000 Stacking Storage Drawers,32.480,2,0.0,4.8720,7,2016,10,2
6826,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,...,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,7,2016,10,2

In [34]:
Segment_of_profit = df.pivot_table( index='Segment',values='Profit', aggfunc=['sum'])
Segment_of_profit.reset_index(inplace=True)
Segment_of_profit

       Segment          sum
                     Profit
0     Consumer  134119.2092
1    Corporate   91979.1340
2  Home Office   60298.6785

In [35]:
Segment_of_sales = df.pivot_table( index='Segment',values='Sales', aggfunc=['sum'])
Segment_of_sales.reset_index(inplace=True)
Segment_of_sales

       Segment           sum
                       Sales
0     Consumer  1.161401e+06
1    Corporate  7.061464e+05
2  Home Office  4.296531e+05

In [36]:
City_of_profit = df.pivot_table( index='City',values='Profit', aggfunc='sum')
City_of_profit.reset_index(inplace=True)
City_of_profit.sort_values(by='Profit', ascending=False, inplace=True)
City_of_profit.head(5)

              City      Profit
329  New York City  62036.9837
266    Los Angeles  30440.7579
452        Seattle  29156.0967
438  San Francisco  17507.3854
123        Detroit  13181.7908

In [37]:
City_of_profit = df.pivot_table( index='City',values='Profit', aggfunc='sum')
City_of_profit.reset_index(inplace=True)
City_of_profit.sort_values(by='Profit', ascending=True, inplace=True)
City_of_profit.head(5)

             City      Profit
374  Philadelphia -13837.7674
207       Houston -10153.5485
434   San Antonio  -7299.0502
241     Lancaster  -7239.0684
80        Chicago  -6654.5688

In [38]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Discount', 'Profit', 'AVG Shipping Time',
       'year_of_order', 'month_of_order', 'day_of_order'],
      dtype='object')

In [39]:
df['Region'].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [40]:
Region_of_profit = df.pivot_table( index='Region',values='Profit', aggfunc='sum')
Region_of_profit.reset_index(inplace=True)
Region_of_profit.sort_values(by='Profit', ascending=False, inplace=True)
Region_of_profit

    Region       Profit
3     West  108418.4489
1     East   91522.7800
2    South   46749.4303
0  Central   39706.3625

In [41]:
Sub_Category_of_sales = df.pivot_table( index='Sub-Category',values='Sales', aggfunc='sum')
Sub_Category_of_sales.reset_index(inplace=True)
Sub_Category_of_sales.sort_values(by='Sales', ascending=False, inplace=True)
Sub_Category_of_sales

   Sub-Category        Sales
13       Phones  330007.0540
5        Chairs  328449.1030
14      Storage  223843.6080
16       Tables  206965.5320
3       Binders  203412.7330
11     Machines  189238.6310
0   Accessories  167380.3180
6       Copiers  149528.0300
4     Bookcases  114879.9963
1    Appliances  107532.1610
9   Furnishings   91705.1640
12        Paper   78479.2060
15     Supplies   46673.5380
2           Art   27118.7920
7     Envelopes   16476.4020
10       Labels   12486.3120
8     Fasteners    3024.2800

In [48]:
Sub_Category_of_profit = df.pivot_table( index='Sub-Category',values='Profit', aggfunc='mean')
Sub_Category_of_profit.reset_index(inplace=True)
Sub_Category_of_profit.sort_values(by='Profit', ascending=False, inplace=True)
Sub_Category_of_profit

   Sub-Category      Profit
6       Copiers  817.909190
0   Accessories   54.111788
13       Phones   50.073938
5        Chairs   43.095894
1    Appliances   38.922758
11     Machines   29.432669
7     Envelopes   27.418019
14      Storage   25.152277
12        Paper   24.856620
3       Binders   19.843574
10       Labels   15.236962
9   Furnishings   13.645918
2           Art    8.200737
8     Fasteners    4.375660
15     Supplies   -6.258418
4     Bookcases  -15.230509
16       Tables  -55.565771

In [51]:
Sub_Category_of_minus_profit = df.pivot_table( index='Sub-Category',values='Profit', aggfunc='sum')
Sub_Category_of_minus_profit.reset_index(inplace=True)
Sub_Category_of_minus_profit.sort_values(by='Profit', ascending=True, inplace=True)
Sub_Category_of_minus_profit.head(3)

   Sub-Category      Profit
16       Tables -17725.4811
4     Bookcases  -3472.5560
15     Supplies  -1189.0995

In [43]:
Category_of_profit = df.pivot_table( index='Category',values='Profit', aggfunc='mean')
Category_of_profit.reset_index(inplace=True)
Category_of_profit.sort_values(by='Profit', ascending=False, inplace=True)
Category_of_profit

          Category     Profit
2       Technology  78.752002
1  Office Supplies  20.327050
0        Furniture   8.699327

In [54]:
df['Profit margin'] = df['Profit'] / df['Sales']*100

In [55]:
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,...,Product Name,Sales,Quantity,Discount,Profit,AVG Shipping Time,year_of_order,month_of_order,day_of_order,Profit margin
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,3,2016,11,8,16.00
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,3,2016,11,8,30.00
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,4,2016,6,12,47.00
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,7,2015,10,11,-40.00
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,7,2015,10,11,11.25

In [59]:
Category_of_profit_margin = df.pivot_table( index='Category',values='Profit margin', aggfunc='mean')
Category_of_profit_margin.reset_index(inplace=True)
Category_of_profit_margin.sort_values(by='Profit margin', ascending=False, inplace=True)
Category_of_profit_margin

          Category  Profit margin
2       Technology      15.613805
1  Office Supplies      13.803029
0        Furniture       3.878353

In [60]:
Sub_Category_of_profit_margin = df.pivot_table( index='Sub-Category',values='Profit margin', aggfunc='mean')
Sub_Category_of_profit_margin.reset_index(inplace=True)
Sub_Category_of_profit_margin.sort_values(by='Profit margin', ascending=False, inplace=True)
Sub_Category_of_profit_margin.head(10)

   Sub-Category  Profit margin
10       Labels      42.966346
12        Paper      42.560036
7     Envelopes      42.313976
6       Copiers      31.719363
8     Fasteners      29.917051
2           Art      25.164573
0   Accessories      21.820968
9   Furnishings      13.706635
13       Phones      11.922197
15     Supplies      11.203947